version: 2.1

orbs:
    rn: react-native-community/react-native@8.0.0
    android: circleci/android@3.1.0

commands:
    install_init:
        steps:
            - rn/yarn_install
            - run:
                  name: Install Global CLI Tools
                  command: |
                      npm install -g detox-cli react-native-cli
                      react-native --version

jobs:
    checking:
        executor:
            name: rn/linux_js
            node_version: "20.18.0"

        steps:
            - checkout
            - install_init
            - run:
                  command: yarn checker // run linter, prettier, jest
            - persist_to_workspace:
                  paths:
                      - .
                  root: .

    test_android:
        executor:
            name: android/android_machine
            resource_class: large
            tag: default

        steps:
            - attach_workspace:
                  at: .
            - rn/android_emulator_start:
                  build_tools_version: "33.0.0"
                  device_name: Pixel_8_API_35
                  platform_version: android-35
            - install_init
            - rn/metro_start
            - run:
                  name: Detox Test
                  command: yarn detox:test:android -l verbose

workflows:
    e2e_test:
        jobs:
            - checking
            - rn/android_build:
                  name: build_android
                  build_image_version: "v15.0"
                  resource_class: large
                  build_cache: false
                  gradle_options: "-Xmx4g -XX:MaxMetaspaceSize=512m"
                  build_type: debug
                  requires:
                      - checking
            - test_android:
                  requires:
                      - build_android
